services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: mountacir
      POSTGRES_PASSWORD: password
#      POSTGRES_DB: customer
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge
volumes:
  db:
