server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: mountacir
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet

  spring:
    jpa:
      hibernate:
        format_sql: true
    main:
      web-application-type: servlet

  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS}
