server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: mountacir
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT.EXPIRATION-MS}

aws:
  s3:
    endpoint: http://localhost:9000
    bucket-name: images
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    region: us-east-1
