server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT.EXPIRATION-MS}

aws:
  s3:
    endpoint: http://localhost:9000
    bucket-name: images
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    region: us-east-1
